### ISSUE TITLE
feat: pre-commit config file

### ISSUE THREAD

**Issue by BaptisteCecconi** [clnsmth/soso#224]
In order to ease the preparation of contribution, it would be good to use pre-commit, so that code checks can be done automatically before the the PR merge checks. 

I see that `black` and `pylint` are used in the `ci-cd.yml` file. 

I will propose a `.pre-commit-config.yml` in the next PR.

**Comment by BaptisteCecconi** [comment]
The pre-commit config file is proposed in PR #225 (and in [6a3ef25](https://github.com/clnsmth/soso/pull/225/commits/6a3ef2541c1272563fe79421c5c41f2518149fec))

**Comment by clnsmth** [comment]
Great idea @BaptisteCecconi. I will need some time to read up on this and test it out before integrating into the system.

**Comment by clnsmth** [comment]
## Note

This uses: https://github.com/pre-commit/pre-commit-hooks?tab=readme-ov-file

A potential configuration for this project (provided by @BaptisteCecconi):

```
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  - id: check-yaml
  - id: end-of-file-fixer
    exclude: .*\.json$
  - id: trailing-whitespace
- repo: https://github.com/psf/black
  rev: 23.7.0
  hooks:
  - id: black
- repo: local
  hooks:
  - id: pylint
    name: pylint
    entry: pylint
    language: system
    types: [python]
    require_serial: true
    args:
      [
        "--exit-zero",
        "--disable=C0103,W0621,R0904"
      ]
```
